import { FlaskConical, Database, Filter, GitBranch, Split, Cpu, TrendingUp, LineChart, AlertTriangle, Sprout } from 'lucide-react';
import { Link } from 'react-router-dom';

export function MethodologyPage() {
  return (
    <div className="mx-auto max-w-7xl px-4 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold tracking-tight text-neutral-900">Methodology</h1>
        <p className="mt-1 text-neutral-600">
          Complete documentation of the data science pipeline behind the groundwater forecasting system
        </p>
      </div>

      {/* Scientific disclaimer */}
      <div className="mb-8 rounded-2xl border border-amber-200 bg-amber-50 p-6">
        <div className="flex items-start gap-3">
          <AlertTriangle className="mt-0.5 shrink-0 text-amber-600" size={24} />
          <div>
            <h2 className="text-base font-semibold text-amber-900">Scientific Disclaimer</h2>
            <p className="mt-1 text-sm text-amber-800">
              Model forecasts are estimates generated by a machine learning model trained on historical data.
              They are not guaranteed groundwater conditions and should not be used as the sole basis for
              irrigation, cropping, or policy decisions. Actual groundwater levels depend on many factors
              not fully captured in the model, including aquifer heterogeneity, pumping patterns, and
              climate variability. Always validate predictions with field measurements.
            </p>
          </div>
        </div>
      </div>

      <div className="space-y-6">
        <MethodStep
          num={1}
          icon={Database}
          title="Real CGWB Data Collection"
          alt
        >
          <p>
            The system operates on actual observational groundwater records from the Central Ground Water Board
            (CGWB) for Ludhiana District, Punjab covering 1994 to 2025:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1 text-sm">
            <li><strong>1,809 real observations:</strong> Actual field measurements recorded by CGWB monitoring wells across Ludhiana district.</li>
            <li><strong>124 physical monitoring stations:</strong> Identified using stable location and GPS coordinate identifiers.</li>
            <li><strong>Observation rounds:</strong> Pre-Monsoon (May) and Winter (January) monitoring cycles.</li>
            <li><strong>Depth measurements:</strong> Groundwater depth in meters below ground level (mbgl).</li>
          </ul>
          <p className="mt-2 text-sm">
            Data is stored locally as <code className="rounded bg-neutral-100 px-1.5 py-0.5 text-xs">backend/data/cgwb_data.csv</code>.
            No synthetic groundwater data or fabricated agricultural/rainfall variables are introduced into the hydrogeological training pipeline.
          </p>
        </MethodStep>

        <MethodStep num={2} icon={Filter} title="Data Cleaning & Leakage Prevention">
          <p>
            Raw data is cleaned using strict temporal ordering and aggregation to preserve all observations without leakage:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1 text-sm">
            <li><strong>Well-specific identification:</strong> Stations are identified using composite keys (location name + latitude + longitude) to prevent merging physically distinct wells.</li>
            <li><strong>Duplicate dates:</strong> Duplicate readings for the exact same station and date are averaged, preserving valid measurements without data loss.</li>
            <li><strong>Strict chronological sorting:</strong> Observations for each monitoring station are sorted chronologically.</li>
            <li><strong>Zero future leakage:</strong> Autoregressive lags use strictly prior observations (<code className="rounded bg-neutral-100 px-1 py-0.5 text-xs">shift(1)</code>, <code className="rounded bg-neutral-100 px-1 py-0.5 text-xs">shift(2)</code>). The historical expanding mean strictly uses prior observations only. Imputer and scaler statistics are learned solely on the training fold.</li>
          </ul>
        </MethodStep>

        <MethodStep num={3} icon={GitBranch} title="Feature Engineering" alt>
          <p>
            The cleaned observations are transformed into model-ready features incorporating spatial, temporal, and autoregressive dynamics:
          </p>
          <div className="mt-3 overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-neutral-200 text-left">
                  <th className="py-2 pr-4 font-semibold text-neutral-700">Feature</th>
                  <th className="py-2 pr-4 font-semibold text-neutral-700">Description</th>
                </tr>
              </thead>
              <tbody>
                {FEATURES_TABLE.map((f) => (
                  <tr key={f.name} className="border-b border-neutral-50">
                    <td className="py-2 pr-4 font-mono text-xs text-primary-700">{f.name}</td>
                    <td className="py-2 pr-4 text-neutral-600">{f.desc}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </MethodStep>

        <MethodStep num={4} icon={Sprout} title="Regional Agricultural Context & Advisory">
          <p>
            The rice-wheat rotation is the dominant agricultural cropping system in Ludhiana District. While the local hydrogeological model predicts groundwater levels directly from empirical well observations:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1 text-sm">
            <li><strong>Kharif Rice Season:</strong> Intensive tube-well pumping for paddy puddling is strongly associated with peak seasonal drawdown between May and October.</li>
            <li><strong>Rabi Wheat Season:</strong> Moderate irrigation demand allows partial stabilization of water tables during winter months.</li>
            <li><strong>Decision-Support Advisory:</strong> Model forecasts directly inform crop diversification, alternate wetting and drying (AWD), and water budgeting advisories.</li>
          </ul>
        </MethodStep>

        <MethodStep num={5} icon={Split} title="Temporal Train/Test Split" alt>
          <p>
            Because the data is temporal (time series of groundwater observations), a standard random train/test
            split would leak future information into training. Instead, a <strong>chronological split</strong> is used:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1 text-sm">
            <li>Data is sorted by year</li>
            <li>The most recent 20% of years form the test set</li>
            <li>All earlier years form the training set</li>
            <li>No shuffling — the model is evaluated on "future" data it has never seen</li>
          </ul>
          <p className="mt-2 text-sm">
            This mimics real-world forecasting: the model learns from historical data and is tested on its ability
            to predict groundwater levels in subsequent years.
          </p>
        </MethodStep>

        <MethodStep num={6} icon={Cpu} title="Model Training">
          <p>
            Four candidate models are trained and compared:
          </p>
          <div className="mt-3 grid gap-3 sm:grid-cols-2">
            {MODELS.map((m) => (
              <div key={m.name} className="rounded-lg border border-neutral-200 bg-white p-4">
                <h4 className="font-semibold text-neutral-900">{m.name}</h4>
                <p className="mt-1 text-sm text-neutral-600">{m.desc}</p>
              </div>
            ))}
          </div>
          <p className="mt-3 text-sm">
            Each model is wrapped in a scikit-learn <strong>Pipeline</strong> that includes a <code className="rounded bg-neutral-100 px-1 py-0.5 text-xs">StandardScaler</code> for
            feature normalization. This ensures the same preprocessing is applied at both training and inference time.
          </p>
        </MethodStep>

        <MethodStep num={7} icon={TrendingUp} title="Model Evaluation" alt>
          <p>
            Models are evaluated on the held-out test set using three metrics:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1 text-sm">
            <li><strong>MAE (Mean Absolute Error):</strong> Average absolute difference between predicted and actual groundwater levels, in meters. Lower is better.</li>
            <li><strong>RMSE (Root Mean Squared Error):</strong> Square root of the average squared error. Penalizes large errors more heavily. Lower is better.</li>
            <li><strong>R² (Coefficient of Determination):</strong> Proportion of variance in the target explained by the model (0 to 1). Higher is better.</li>
          </ul>
          <p className="mt-2 text-sm">
            The model with the lowest RMSE is selected as the final model. All metrics and model comparisons
            are displayed on the <Link to="/model" className="text-primary-600 underline">Model Info</Link> page —
            no metrics are hard-coded or fabricated.
          </p>
        </MethodStep>

        <MethodStep num={8} icon={LineChart} title="Scenario-Based Groundwater Projection">
          <p>
            For a given block, the system generates multi-year scenario projections under clearly defined assumptions:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1 text-sm">
            <li><strong>Status-Quo Baseline Scenario:</strong> Future rainfall, crop acreage (rice and wheat), extraction volume, and irrigation intensity are held constant at the latest observed baseline levels.</li>
            <li><strong>Autoregressive Lag Projection:</strong> For each future period, predicted groundwater levels feed back autoregressively as lag inputs for subsequent steps.</li>
            <li><strong>Conditional Scope:</strong> These projections represent conditional scenarios rather than unconditional guarantees.</li>
          </ul>
          <p className="mt-2 rounded bg-amber-50 px-3 py-2 text-sm text-amber-800">
            Note: Projections indicate trajectories under status-quo conditions and accumulate uncertainty over longer horizons.
          </p>
        </MethodStep>

        <MethodStep num={9} icon={AlertTriangle} title="Groundwater Depletion Risk Classification" alt>
          <p>
            Predicted groundwater conditions are categorized into four risk tiers using <strong>Project-Defined Heuristic Thresholds</strong>.
            These provide practical decision-support guidelines and are not statutory CGWB regulatory standards:
          </p>
          <div className="mt-3 overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-neutral-200 text-left">
                  <th className="py-2 pr-4 font-semibold text-neutral-700">Risk Level</th>
                  <th className="py-2 pr-4 font-semibold text-neutral-700">Project Decision-Support Criteria</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-neutral-50"><td className="py-2 pr-4"><span className="rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-semibold text-green-700">Low</span></td><td className="py-2 pr-4 text-neutral-600">GW depth &lt; 12 mbgl and annual depletion &lt; 0.5 m/yr</td></tr>
                <tr className="border-b border-neutral-50"><td className="py-2 pr-4"><span className="rounded-full bg-yellow-100 px-2.5 py-0.5 text-xs font-semibold text-yellow-700">Moderate</span></td><td className="py-2 pr-4 text-neutral-600">GW depth 12–18 mbgl or annual depletion 0.5–1.0 m/yr</td></tr>
                <tr className="border-b border-neutral-50"><td className="py-2 pr-4"><span className="rounded-full bg-orange-100 px-2.5 py-0.5 text-xs font-semibold text-orange-700">High</span></td><td className="py-2 pr-4 text-neutral-600">GW depth 18–25 mbgl or annual depletion 1.0–1.5 m/yr</td></tr>
                <tr className="border-b border-neutral-50"><td className="py-2 pr-4"><span className="rounded-full bg-red-100 px-2.5 py-0.5 text-xs font-semibold text-red-700">Critical</span></td><td className="py-2 pr-4 text-neutral-600">GW depth ≥ 25 mbgl or annual depletion ≥ 1.5 m/yr</td></tr>
              </tbody>
            </table>
          </div>
        </MethodStep>

        <MethodStep num={10} icon={Sprout} title="Farmer Advisory" alt>
          <p>
            The advisory engine is a <strong>rule-based system</strong> (not a machine learning model) that
            generates practical recommendations based on:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1 text-sm">
            <li>The predicted groundwater level and depletion rate from the ML model</li>
            <li>The risk classification</li>
            <li>Season (Kharif, Rabi, Pre-Monsoon, Post-Monsoon)</li>
            <li>Rainfall, rice area, wheat area, and irrigation intensity from user input</li>
          </ul>
          <p className="mt-2 text-sm">
            Recommendations cover water-efficient irrigation, irrigation scheduling, reducing pumping, crop
            diversification, groundwater monitoring, rainwater harvesting, and alternative irrigation methods.
          </p>
          <div className="mt-3 rounded-lg bg-purple-50 px-4 py-3 text-sm text-purple-800">
            <strong>ADVISORY</strong> recommendations are educational and decision-support only. They do not
            guarantee any specific agricultural outcome. Always consult local agricultural extension services
            for field-specific guidance.
          </div>
        </MethodStep>
      </div>

      {/* Pipeline summary */}
      <div className="mt-12 rounded-2xl border border-primary-100 bg-gradient-to-br from-primary-50 to-white p-6">
        <h2 className="mb-4 flex items-center gap-2 text-lg font-semibold text-primary-900">
          <FlaskConical size={20} />
          Pipeline Summary
        </h2>
        <div className="flex flex-wrap items-center gap-2 text-sm">
          {['Raw CSV', 'Clean', 'Features', 'Split', 'Train', 'Evaluate', 'Select', 'Save', 'Predict', 'Advisory'].map((step, i, arr) => (
            <span key={step} className="flex items-center gap-2">
              <span className="rounded-lg border border-primary-200 bg-white px-3 py-1.5 font-medium text-primary-800">{step}</span>
              {i < arr.length - 1 && <span className="text-primary-400">→</span>}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

const FEATURES_TABLE = [
  { name: 'year', desc: 'Calendar year of observation (temporal drift indicator)' },
  { name: 'month', desc: 'Calendar month of observation (5 for Pre-Monsoon, 1 for January)' },
  { name: 'measurement_period', desc: 'Binary observation round indicator: 1 = Pre-Monsoon (May), 0 = Winter (January)' },
  { name: 'latitude', desc: 'Spatial GPS latitude of monitoring well' },
  { name: 'longitude', desc: 'Spatial GPS longitude of monitoring well' },
  { name: 'lag_1_mbgl', desc: 'Immediate prior groundwater depth observation at the exact station (m bgl)' },
  { name: 'lag_2_mbgl', desc: 'Penultimate prior groundwater depth observation at the exact station (m bgl)' },
  { name: 'historical_mean_mbgl', desc: 'Expanding average of all preceding observations at the station (strict no-leakage)' },
];

const MODELS = [
  { name: 'Linear Regression', desc: 'Simple baseline model. Assumes linear relationship between features and groundwater level.' },
  { name: 'Random Forest', desc: 'Ensemble of decision trees. Captures non-linear patterns and feature interactions.' },
  { name: 'Gradient Boosting', desc: 'Sequential ensemble that builds trees to correct residual errors. Often strong on tabular data.' },
  { name: 'Hist Gradient Boosting', desc: 'Faster scikit-learn implementation using histogram-based splitting. Scales well to larger datasets.' },
];

function MethodStep({
  num,
  icon: Icon,
  title,
  children,
  alt,
}: {
  num: number;
  icon: React.ElementType;
  title: string;
  children: React.ReactNode;
  alt?: boolean;
}) {
  return (
    <div className={`rounded-2xl border border-neutral-200 p-6 shadow-sm ${alt ? 'bg-neutral-50' : 'bg-white'}`}>
      <div className="mb-3 flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-600 text-white">
          <Icon size={20} />
        </div>
        <div className="flex items-baseline gap-2">
          <span className="text-sm font-bold text-primary-600">Step {num}</span>
          <h2 className="text-lg font-semibold text-neutral-900">{title}</h2>
        </div>
      </div>
      <div className="ml-13 text-sm text-neutral-700">
        {children}
      </div>
    </div>
  );
}
